apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  generation: 3
  labels:
    app: whored
  name: whored
  namespace: default
  resourceVersion: "1906115"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/whored
  uid: e8afa5d1-6eca-11e9-862c-000c2937d745
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: whored
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: whored
    spec:
      containers:
      - image: robinpeter/imred
        imagePullPolicy: Always
        name: imred
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "200m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
