apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    field.cattle.io/publicEndpoints: '[{"addresses":["192.168.8.220"],"port":80,"protocol":"HTTP","serviceName":"default:whored","ingressName":"default:whoami-ingress","hostname":"red.example.com","path":"/","allNodes":false}]'
  creationTimestamp: "2019-05-05T00:15:37Z"
  generation: 3
  labels:
    app: whored
  name: whored
  namespace: default
  resourceVersion: "1906115"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/whored
  uid: e8afa5d1-6eca-11e9-862c-000c2937d745
spec:
  progressDeadlineSeconds: 600
  replicas: 4
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: whored
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: whored
    spec:
      containers:
      - image: robinpeter/imred
        imagePullPolicy: Always
        name: imred
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: "16Mi"
            cpu: "100m"
          limits:
            memory: "32Mi"
            cpu: "200m"
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 4
  conditions:
  - lastTransitionTime: "2019-05-05T00:15:41Z"
    lastUpdateTime: "2019-05-05T00:15:41Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2019-05-05T00:15:37Z"
    lastUpdateTime: "2019-05-05T00:15:42Z"
    message: ReplicaSet "whored-67f966cfbd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 4
  replicas: 4
  updatedReplicas: 4
